// Netsy <https://netsy.dev>
// Copyright The Netsy Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/elector.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Elector_RegisterNode_FullMethodName    = "/netsy.Elector/RegisterNode"
	Elector_DeregisterNode_FullMethodName  = "/netsy.Elector/DeregisterNode"
	Elector_GetClusterState_FullMethodName = "/netsy.Elector/GetClusterState"
	Elector_SendHeartbeat_FullMethodName   = "/netsy.Elector/SendHeartbeat"
	Elector_GetMemberList_FullMethodName   = "/netsy.Elector/GetMemberList"
)

// ElectorClient is the client API for Elector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Elector service — hosted by the Elector Node for registration,
// cluster state queries, and heartbeat collection.
type ElectorClient interface {
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	DeregisterNode(ctx context.Context, in *DeregisterNodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetClusterState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterState, error)
	SendHeartbeat(ctx context.Context, in *NodeState, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetMemberList(ctx context.Context, in *GetMemberListRequest, opts ...grpc.CallOption) (*GetMemberListResponse, error)
}

type electorClient struct {
	cc grpc.ClientConnInterface
}

func NewElectorClient(cc grpc.ClientConnInterface) ElectorClient {
	return &electorClient{cc}
}

func (c *electorClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, Elector_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *electorClient) DeregisterNode(ctx context.Context, in *DeregisterNodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Elector_DeregisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *electorClient) GetClusterState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterState)
	err := c.cc.Invoke(ctx, Elector_GetClusterState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *electorClient) SendHeartbeat(ctx context.Context, in *NodeState, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Elector_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *electorClient) GetMemberList(ctx context.Context, in *GetMemberListRequest, opts ...grpc.CallOption) (*GetMemberListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberListResponse)
	err := c.cc.Invoke(ctx, Elector_GetMemberList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ElectorServer is the server API for Elector service.
// All implementations must embed UnimplementedElectorServer
// for forward compatibility.
//
// Elector service — hosted by the Elector Node for registration,
// cluster state queries, and heartbeat collection.
type ElectorServer interface {
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	DeregisterNode(context.Context, *DeregisterNodeRequest) (*emptypb.Empty, error)
	GetClusterState(context.Context, *emptypb.Empty) (*ClusterState, error)
	SendHeartbeat(context.Context, *NodeState) (*emptypb.Empty, error)
	GetMemberList(context.Context, *GetMemberListRequest) (*GetMemberListResponse, error)
	mustEmbedUnimplementedElectorServer()
}

// UnimplementedElectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedElectorServer struct{}

func (UnimplementedElectorServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedElectorServer) DeregisterNode(context.Context, *DeregisterNodeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeregisterNode not implemented")
}
func (UnimplementedElectorServer) GetClusterState(context.Context, *emptypb.Empty) (*ClusterState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterState not implemented")
}
func (UnimplementedElectorServer) SendHeartbeat(context.Context, *NodeState) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedElectorServer) GetMemberList(context.Context, *GetMemberListRequest) (*GetMemberListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberList not implemented")
}
func (UnimplementedElectorServer) mustEmbedUnimplementedElectorServer() {}
func (UnimplementedElectorServer) testEmbeddedByValue()                 {}

// UnsafeElectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ElectorServer will
// result in compilation errors.
type UnsafeElectorServer interface {
	mustEmbedUnimplementedElectorServer()
}

func RegisterElectorServer(s grpc.ServiceRegistrar, srv ElectorServer) {
	// If the following call pancis, it indicates UnimplementedElectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Elector_ServiceDesc, srv)
}

func _Elector_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElectorServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Elector_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElectorServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Elector_DeregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElectorServer).DeregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Elector_DeregisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElectorServer).DeregisterNode(ctx, req.(*DeregisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Elector_GetClusterState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElectorServer).GetClusterState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Elector_GetClusterState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElectorServer).GetClusterState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Elector_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElectorServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Elector_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElectorServer).SendHeartbeat(ctx, req.(*NodeState))
	}
	return interceptor(ctx, in, info, handler)
}

func _Elector_GetMemberList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElectorServer).GetMemberList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Elector_GetMemberList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElectorServer).GetMemberList(ctx, req.(*GetMemberListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Elector_ServiceDesc is the grpc.ServiceDesc for Elector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Elector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netsy.Elector",
	HandlerType: (*ElectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _Elector_RegisterNode_Handler,
		},
		{
			MethodName: "DeregisterNode",
			Handler:    _Elector_DeregisterNode_Handler,
		},
		{
			MethodName: "GetClusterState",
			Handler:    _Elector_GetClusterState_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _Elector_SendHeartbeat_Handler,
		},
		{
			MethodName: "GetMemberList",
			Handler:    _Elector_GetMemberList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/elector.proto",
}
