// Netsy <https://netsy.dev>
// Copyright The Netsy Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MinWatchRevisionResponse returns the lowest revision held by any active
// Watch on this Node. Used by the Primary to compute a safe compaction point.
type MinWatchRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinRevision   int64                  `protobuf:"varint,1,opt,name=min_revision,json=minRevision,proto3" json:"min_revision,omitempty"` // if no active Watches exist, return current committed_revision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinWatchRevisionResponse) Reset() {
	*x = MinWatchRevisionResponse{}
	mi := &file_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinWatchRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinWatchRevisionResponse) ProtoMessage() {}

func (x *MinWatchRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinWatchRevisionResponse.ProtoReflect.Descriptor instead.
func (*MinWatchRevisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

func (x *MinWatchRevisionResponse) GetMinRevision() int64 {
	if x != nil {
		return x.MinRevision
	}
	return 0
}

// CompactionNotice is sent by the Primary to every Node proposing a new
// compaction revision. Each Node must atomically validate that no active
// Watch would be invalidated before confirming.
type CompactionNotice struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CompactionRevision int64                  `protobuf:"varint,1,opt,name=compaction_revision,json=compactionRevision,proto3" json:"compaction_revision,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompactionNotice) Reset() {
	*x = CompactionNotice{}
	mi := &file_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactionNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactionNotice) ProtoMessage() {}

func (x *CompactionNotice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactionNotice.ProtoReflect.Descriptor instead.
func (*CompactionNotice) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *CompactionNotice) GetCompactionRevision() int64 {
	if x != nil {
		return x.CompactionRevision
	}
	return 0
}

// CompactionNoticeResponse indicates whether the Node accepted the proposed
// compaction revision. Rejection means an active Watch exists below it.
type CompactionNoticeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmed     bool                   `protobuf:"varint,1,opt,name=confirmed,proto3" json:"confirmed,omitempty"` // confirms the Node has accepted the proposed compaction revision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactionNoticeResponse) Reset() {
	*x = CompactionNoticeResponse{}
	mi := &file_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactionNoticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactionNoticeResponse) ProtoMessage() {}

func (x *CompactionNoticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactionNoticeResponse.ProtoReflect.Descriptor instead.
func (*CompactionNoticeResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *CompactionNoticeResponse) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

var File_proto_node_proto protoreflect.FileDescriptor

const file_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x10proto/node.proto\x12\x05netsy\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11proto/state.proto\"=\n" +
	"\x18MinWatchRevisionResponse\x12!\n" +
	"\fmin_revision\x18\x01 \x01(\x03R\vminRevision\"C\n" +
	"\x10CompactionNotice\x12/\n" +
	"\x13compaction_revision\x18\x01 \x01(\x03R\x12compactionRevision\"8\n" +
	"\x18CompactionNoticeResponse\x12\x1c\n" +
	"\tconfirmed\x18\x01 \x01(\bR\tconfirmed2\xa3\x02\n" +
	"\x04Node\x12?\n" +
	"\x10PushClusterState\x12\x13.netsy.ClusterState\x1a\x16.google.protobuf.Empty\x128\n" +
	"\fGetNodeState\x12\x16.google.protobuf.Empty\x1a\x10.netsy.NodeState\x12N\n" +
	"\x13GetMinWatchRevision\x12\x16.google.protobuf.Empty\x1a\x1f.netsy.MinWatchRevisionResponse\x12P\n" +
	"\x14SendCompactionNotice\x12\x17.netsy.CompactionNotice\x1a\x1f.netsy.CompactionNoticeResponseB+Z)github.com/netsy-dev/netsy/internal/protob\x06proto3"

var (
	file_proto_node_proto_rawDescOnce sync.Once
	file_proto_node_proto_rawDescData []byte
)

func file_proto_node_proto_rawDescGZIP() []byte {
	file_proto_node_proto_rawDescOnce.Do(func() {
		file_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)))
	})
	return file_proto_node_proto_rawDescData
}

var file_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_node_proto_goTypes = []any{
	(*MinWatchRevisionResponse)(nil), // 0: netsy.MinWatchRevisionResponse
	(*CompactionNotice)(nil),         // 1: netsy.CompactionNotice
	(*CompactionNoticeResponse)(nil), // 2: netsy.CompactionNoticeResponse
	(*ClusterState)(nil),             // 3: netsy.ClusterState
	(*emptypb.Empty)(nil),            // 4: google.protobuf.Empty
	(*NodeState)(nil),                // 5: netsy.NodeState
}
var file_proto_node_proto_depIdxs = []int32{
	3, // 0: netsy.Node.PushClusterState:input_type -> netsy.ClusterState
	4, // 1: netsy.Node.GetNodeState:input_type -> google.protobuf.Empty
	4, // 2: netsy.Node.GetMinWatchRevision:input_type -> google.protobuf.Empty
	1, // 3: netsy.Node.SendCompactionNotice:input_type -> netsy.CompactionNotice
	4, // 4: netsy.Node.PushClusterState:output_type -> google.protobuf.Empty
	5, // 5: netsy.Node.GetNodeState:output_type -> netsy.NodeState
	0, // 6: netsy.Node.GetMinWatchRevision:output_type -> netsy.MinWatchRevisionResponse
	2, // 7: netsy.Node.SendCompactionNotice:output_type -> netsy.CompactionNoticeResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_node_proto_init() }
func file_proto_node_proto_init() {
	if File_proto_node_proto != nil {
		return
	}
	file_proto_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_proto_goTypes,
		DependencyIndexes: file_proto_node_proto_depIdxs,
		MessageInfos:      file_proto_node_proto_msgTypes,
	}.Build()
	File_proto_node_proto = out.File
	file_proto_node_proto_goTypes = nil
	file_proto_node_proto_depIdxs = nil
}
