// Netsy <https://netsy.dev>
// Copyright The Netsy Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/node.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Node_PushClusterState_FullMethodName     = "/netsy.Node/PushClusterState"
	Node_GetNodeState_FullMethodName         = "/netsy.Node/GetNodeState"
	Node_GetMinWatchRevision_FullMethodName  = "/netsy.Node/GetMinWatchRevision"
	Node_SendCompactionNotice_FullMethodName = "/netsy.Node/SendCompactionNotice"
)

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Node service — hosted by every Node, called by the Elector and Primary
// for cluster state pushes, node state queries, and compaction coordination.
type NodeClient interface {
	PushClusterState(ctx context.Context, in *ClusterState, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetNodeState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeState, error)
	GetMinWatchRevision(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MinWatchRevisionResponse, error)
	SendCompactionNotice(ctx context.Context, in *CompactionNotice, opts ...grpc.CallOption) (*CompactionNoticeResponse, error)
}

type nodeClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeClient(cc grpc.ClientConnInterface) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) PushClusterState(ctx context.Context, in *ClusterState, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Node_PushClusterState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetNodeState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeState)
	err := c.cc.Invoke(ctx, Node_GetNodeState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetMinWatchRevision(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MinWatchRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MinWatchRevisionResponse)
	err := c.cc.Invoke(ctx, Node_GetMinWatchRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) SendCompactionNotice(ctx context.Context, in *CompactionNotice, opts ...grpc.CallOption) (*CompactionNoticeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactionNoticeResponse)
	err := c.cc.Invoke(ctx, Node_SendCompactionNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
// All implementations must embed UnimplementedNodeServer
// for forward compatibility.
//
// Node service — hosted by every Node, called by the Elector and Primary
// for cluster state pushes, node state queries, and compaction coordination.
type NodeServer interface {
	PushClusterState(context.Context, *ClusterState) (*emptypb.Empty, error)
	GetNodeState(context.Context, *emptypb.Empty) (*NodeState, error)
	GetMinWatchRevision(context.Context, *emptypb.Empty) (*MinWatchRevisionResponse, error)
	SendCompactionNotice(context.Context, *CompactionNotice) (*CompactionNoticeResponse, error)
	mustEmbedUnimplementedNodeServer()
}

// UnimplementedNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServer struct{}

func (UnimplementedNodeServer) PushClusterState(context.Context, *ClusterState) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushClusterState not implemented")
}
func (UnimplementedNodeServer) GetNodeState(context.Context, *emptypb.Empty) (*NodeState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeState not implemented")
}
func (UnimplementedNodeServer) GetMinWatchRevision(context.Context, *emptypb.Empty) (*MinWatchRevisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMinWatchRevision not implemented")
}
func (UnimplementedNodeServer) SendCompactionNotice(context.Context, *CompactionNotice) (*CompactionNoticeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCompactionNotice not implemented")
}
func (UnimplementedNodeServer) mustEmbedUnimplementedNodeServer() {}
func (UnimplementedNodeServer) testEmbeddedByValue()              {}

// UnsafeNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServer will
// result in compilation errors.
type UnsafeNodeServer interface {
	mustEmbedUnimplementedNodeServer()
}

func RegisterNodeServer(s grpc.ServiceRegistrar, srv NodeServer) {
	// If the following call pancis, it indicates UnimplementedNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Node_ServiceDesc, srv)
}

func _Node_PushClusterState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).PushClusterState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_PushClusterState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).PushClusterState(ctx, req.(*ClusterState))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetNodeState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetNodeState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_GetNodeState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetNodeState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetMinWatchRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetMinWatchRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_GetMinWatchRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetMinWatchRevision(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_SendCompactionNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactionNotice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).SendCompactionNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Node_SendCompactionNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).SendCompactionNotice(ctx, req.(*CompactionNotice))
	}
	return interceptor(ctx, in, info, handler)
}

// Node_ServiceDesc is the grpc.ServiceDesc for Node service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Node_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netsy.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushClusterState",
			Handler:    _Node_PushClusterState_Handler,
		},
		{
			MethodName: "GetNodeState",
			Handler:    _Node_GetNodeState_Handler,
		},
		{
			MethodName: "GetMinWatchRevision",
			Handler:    _Node_GetMinWatchRevision_Handler,
		},
		{
			MethodName: "SendCompactionNotice",
			Handler:    _Node_SendCompactionNotice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/node.proto",
}
