// Netsy <https://netsy.dev>
// Copyright The Netsy Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/primary.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Primary_Follow_FullMethodName        = "/netsy.Primary/Follow"
	Primary_SendHeartbeat_FullMethodName = "/netsy.Primary/SendHeartbeat"
)

// PrimaryClient is the client API for Primary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Primary service — hosted by the Primary Node for replication streaming
// and standalone heartbeat collection from Replicas.
type PrimaryClient interface {
	Follow(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicaMessage, PrimaryMessage], error)
	SendHeartbeat(ctx context.Context, in *NodeState, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type primaryClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimaryClient(cc grpc.ClientConnInterface) PrimaryClient {
	return &primaryClient{cc}
}

func (c *primaryClient) Follow(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicaMessage, PrimaryMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Primary_ServiceDesc.Streams[0], Primary_Follow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplicaMessage, PrimaryMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Primary_FollowClient = grpc.BidiStreamingClient[ReplicaMessage, PrimaryMessage]

func (c *primaryClient) SendHeartbeat(ctx context.Context, in *NodeState, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Primary_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimaryServer is the server API for Primary service.
// All implementations must embed UnimplementedPrimaryServer
// for forward compatibility.
//
// Primary service — hosted by the Primary Node for replication streaming
// and standalone heartbeat collection from Replicas.
type PrimaryServer interface {
	Follow(grpc.BidiStreamingServer[ReplicaMessage, PrimaryMessage]) error
	SendHeartbeat(context.Context, *NodeState) (*emptypb.Empty, error)
	mustEmbedUnimplementedPrimaryServer()
}

// UnimplementedPrimaryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrimaryServer struct{}

func (UnimplementedPrimaryServer) Follow(grpc.BidiStreamingServer[ReplicaMessage, PrimaryMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedPrimaryServer) SendHeartbeat(context.Context, *NodeState) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedPrimaryServer) mustEmbedUnimplementedPrimaryServer() {}
func (UnimplementedPrimaryServer) testEmbeddedByValue()                 {}

// UnsafePrimaryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimaryServer will
// result in compilation errors.
type UnsafePrimaryServer interface {
	mustEmbedUnimplementedPrimaryServer()
}

func RegisterPrimaryServer(s grpc.ServiceRegistrar, srv PrimaryServer) {
	// If the following call pancis, it indicates UnimplementedPrimaryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Primary_ServiceDesc, srv)
}

func _Primary_Follow_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PrimaryServer).Follow(&grpc.GenericServerStream[ReplicaMessage, PrimaryMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Primary_FollowServer = grpc.BidiStreamingServer[ReplicaMessage, PrimaryMessage]

func _Primary_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimaryServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Primary_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimaryServer).SendHeartbeat(ctx, req.(*NodeState))
	}
	return interceptor(ctx, in, info, handler)
}

// Primary_ServiceDesc is the grpc.ServiceDesc for Primary service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Primary_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netsy.Primary",
	HandlerType: (*PrimaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartbeat",
			Handler:    _Primary_SendHeartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Follow",
			Handler:       _Primary_Follow_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/primary.proto",
}
