// Netsy <https://netsy.dev>
// Copyright The Netsy Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/primary.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Initial is the first message the Primary sends on a new Follow stream,
// providing the Replica with the current committed and compaction revisions.
type Initial struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CommittedRevision  int64                  `protobuf:"varint,1,opt,name=committed_revision,json=committedRevision,proto3" json:"committed_revision,omitempty"`
	CompactionRevision int64                  `protobuf:"varint,2,opt,name=compaction_revision,json=compactionRevision,proto3" json:"compaction_revision,omitempty"` // 0 if no Compaction Revision accepted yet
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Initial) Reset() {
	*x = Initial{}
	mi := &file_proto_primary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Initial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Initial) ProtoMessage() {}

func (x *Initial) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Initial.ProtoReflect.Descriptor instead.
func (*Initial) Descriptor() ([]byte, []int) {
	return file_proto_primary_proto_rawDescGZIP(), []int{0}
}

func (x *Initial) GetCommittedRevision() int64 {
	if x != nil {
		return x.CommittedRevision
	}
	return 0
}

func (x *Initial) GetCompactionRevision() int64 {
	if x != nil {
		return x.CompactionRevision
	}
	return 0
}

// PrimaryMessage is sent from Primary to Replica on the replication stream.
type PrimaryMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PrimaryMessage_Initial
	//	*PrimaryMessage_Record
	//	*PrimaryMessage_Commit
	//	*PrimaryMessage_Compact
	Payload       isPrimaryMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimaryMessage) Reset() {
	*x = PrimaryMessage{}
	mi := &file_proto_primary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryMessage) ProtoMessage() {}

func (x *PrimaryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryMessage.ProtoReflect.Descriptor instead.
func (*PrimaryMessage) Descriptor() ([]byte, []int) {
	return file_proto_primary_proto_rawDescGZIP(), []int{1}
}

func (x *PrimaryMessage) GetPayload() isPrimaryMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PrimaryMessage) GetInitial() *Initial {
	if x != nil {
		if x, ok := x.Payload.(*PrimaryMessage_Initial); ok {
			return x.Initial
		}
	}
	return nil
}

func (x *PrimaryMessage) GetRecord() *Record {
	if x != nil {
		if x, ok := x.Payload.(*PrimaryMessage_Record); ok {
			return x.Record
		}
	}
	return nil
}

func (x *PrimaryMessage) GetCommit() int64 {
	if x != nil {
		if x, ok := x.Payload.(*PrimaryMessage_Commit); ok {
			return x.Commit
		}
	}
	return 0
}

func (x *PrimaryMessage) GetCompact() int64 {
	if x != nil {
		if x, ok := x.Payload.(*PrimaryMessage_Compact); ok {
			return x.Compact
		}
	}
	return 0
}

type isPrimaryMessage_Payload interface {
	isPrimaryMessage_Payload()
}

type PrimaryMessage_Initial struct {
	Initial *Initial `protobuf:"bytes,1,opt,name=initial,proto3,oneof"`
}

type PrimaryMessage_Record struct {
	Record *Record `protobuf:"bytes,2,opt,name=record,proto3,oneof"`
}

type PrimaryMessage_Commit struct {
	Commit int64 `protobuf:"varint,3,opt,name=commit,proto3,oneof"` // committed_revision
}

type PrimaryMessage_Compact struct {
	Compact int64 `protobuf:"varint,4,opt,name=compact,proto3,oneof"` // compaction_revision
}

func (*PrimaryMessage_Initial) isPrimaryMessage_Payload() {}

func (*PrimaryMessage_Record) isPrimaryMessage_Payload() {}

func (*PrimaryMessage_Commit) isPrimaryMessage_Payload() {}

func (*PrimaryMessage_Compact) isPrimaryMessage_Payload() {}

// ReplicaMessage is sent from Replica to Primary on the replication stream.
type ReplicaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`  // the revision being receipted
	Heartbeat     *NodeState             `protobuf:"bytes,2,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"` // embedded heartbeat
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicaMessage) Reset() {
	*x = ReplicaMessage{}
	mi := &file_proto_primary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaMessage) ProtoMessage() {}

func (x *ReplicaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaMessage.ProtoReflect.Descriptor instead.
func (*ReplicaMessage) Descriptor() ([]byte, []int) {
	return file_proto_primary_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicaMessage) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ReplicaMessage) GetHeartbeat() *NodeState {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

var File_proto_primary_proto protoreflect.FileDescriptor

const file_proto_primary_proto_rawDesc = "" +
	"\n" +
	"\x13proto/primary.proto\x12\x05netsy\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12proto/record.proto\x1a\x11proto/state.proto\"i\n" +
	"\aInitial\x12-\n" +
	"\x12committed_revision\x18\x01 \x01(\x03R\x11committedRevision\x12/\n" +
	"\x13compaction_revision\x18\x02 \x01(\x03R\x12compactionRevision\"\xa6\x01\n" +
	"\x0ePrimaryMessage\x12*\n" +
	"\ainitial\x18\x01 \x01(\v2\x0e.netsy.InitialH\x00R\ainitial\x12'\n" +
	"\x06record\x18\x02 \x01(\v2\r.netsy.RecordH\x00R\x06record\x12\x18\n" +
	"\x06commit\x18\x03 \x01(\x03H\x00R\x06commit\x12\x1a\n" +
	"\acompact\x18\x04 \x01(\x03H\x00R\acompactB\t\n" +
	"\apayload\"\\\n" +
	"\x0eReplicaMessage\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12.\n" +
	"\theartbeat\x18\x02 \x01(\v2\x10.netsy.NodeStateR\theartbeat2\x80\x01\n" +
	"\aPrimary\x12:\n" +
	"\x06Follow\x12\x15.netsy.ReplicaMessage\x1a\x15.netsy.PrimaryMessage(\x010\x01\x129\n" +
	"\rSendHeartbeat\x12\x10.netsy.NodeState\x1a\x16.google.protobuf.EmptyB+Z)github.com/netsy-dev/netsy/internal/protob\x06proto3"

var (
	file_proto_primary_proto_rawDescOnce sync.Once
	file_proto_primary_proto_rawDescData []byte
)

func file_proto_primary_proto_rawDescGZIP() []byte {
	file_proto_primary_proto_rawDescOnce.Do(func() {
		file_proto_primary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_primary_proto_rawDesc), len(file_proto_primary_proto_rawDesc)))
	})
	return file_proto_primary_proto_rawDescData
}

var file_proto_primary_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_primary_proto_goTypes = []any{
	(*Initial)(nil),        // 0: netsy.Initial
	(*PrimaryMessage)(nil), // 1: netsy.PrimaryMessage
	(*ReplicaMessage)(nil), // 2: netsy.ReplicaMessage
	(*Record)(nil),         // 3: netsy.Record
	(*NodeState)(nil),      // 4: netsy.NodeState
	(*emptypb.Empty)(nil),  // 5: google.protobuf.Empty
}
var file_proto_primary_proto_depIdxs = []int32{
	0, // 0: netsy.PrimaryMessage.initial:type_name -> netsy.Initial
	3, // 1: netsy.PrimaryMessage.record:type_name -> netsy.Record
	4, // 2: netsy.ReplicaMessage.heartbeat:type_name -> netsy.NodeState
	2, // 3: netsy.Primary.Follow:input_type -> netsy.ReplicaMessage
	4, // 4: netsy.Primary.SendHeartbeat:input_type -> netsy.NodeState
	1, // 5: netsy.Primary.Follow:output_type -> netsy.PrimaryMessage
	5, // 6: netsy.Primary.SendHeartbeat:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_primary_proto_init() }
func file_proto_primary_proto_init() {
	if File_proto_primary_proto != nil {
		return
	}
	file_proto_record_proto_init()
	file_proto_state_proto_init()
	file_proto_primary_proto_msgTypes[1].OneofWrappers = []any{
		(*PrimaryMessage_Initial)(nil),
		(*PrimaryMessage_Record)(nil),
		(*PrimaryMessage_Commit)(nil),
		(*PrimaryMessage_Compact)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_primary_proto_rawDesc), len(file_proto_primary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_primary_proto_goTypes,
		DependencyIndexes: file_proto_primary_proto_depIdxs,
		MessageInfos:      file_proto_primary_proto_msgTypes,
	}.Build()
	File_proto_primary_proto = out.File
	file_proto_primary_proto_goTypes = nil
	file_proto_primary_proto_depIdxs = nil
}
