// Netsy <https://netsy.dev>
// Copyright The Netsy Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/record.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Revision       int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Key            []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Created        bool                   `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Deleted        bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreateRevision int64                  `protobuf:"varint,6,opt,name=create_revision,json=createRevision,proto3" json:"create_revision,omitempty"`
	PrevRevision   int64                  `protobuf:"varint,7,opt,name=prev_revision,json=prevRevision,proto3" json:"prev_revision,omitempty"`
	Version        int64                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"`
	Lease          int64                  `protobuf:"varint,9,opt,name=lease,proto3" json:"lease,omitempty"`
	Dek            int64                  `protobuf:"varint,10,opt,name=dek,proto3" json:"dek,omitempty"` // 0 = value is not encrypted
	Value          []byte                 `protobuf:"bytes,11,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompactedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=compacted_at,json=compactedAt,proto3" json:"compacted_at,omitempty"`
	LeaderId       string                 `protobuf:"bytes,14,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	ReplicatedAt   *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=replicated_at,json=replicatedAt,proto3" json:"replicated_at,omitempty"`
	Crc            uint64                 `protobuf:"varint,1,opt,name=crc,proto3" json:"crc,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_record_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Record) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Record) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *Record) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Record) GetCreateRevision() int64 {
	if x != nil {
		return x.CreateRevision
	}
	return 0
}

func (x *Record) GetPrevRevision() int64 {
	if x != nil {
		return x.PrevRevision
	}
	return 0
}

func (x *Record) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Record) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

func (x *Record) GetDek() int64 {
	if x != nil {
		return x.Dek
	}
	return 0
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Record) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Record) GetCompactedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompactedAt
	}
	return nil
}

func (x *Record) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *Record) GetReplicatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReplicatedAt
	}
	return nil
}

func (x *Record) GetCrc() uint64 {
	if x != nil {
		return x.Crc
	}
	return 0
}

var File_proto_record_proto protoreflect.FileDescriptor

const file_proto_record_proto_rawDesc = "" +
	"\n" +
	"\x12proto/record.proto\x12\x05netsy\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x03\n" +
	"\x06Record\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x18\n" +
	"\acreated\x18\x04 \x01(\bR\acreated\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12'\n" +
	"\x0fcreate_revision\x18\x06 \x01(\x03R\x0ecreateRevision\x12#\n" +
	"\rprev_revision\x18\a \x01(\x03R\fprevRevision\x12\x18\n" +
	"\aversion\x18\b \x01(\x03R\aversion\x12\x14\n" +
	"\x05lease\x18\t \x01(\x03R\x05lease\x12\x10\n" +
	"\x03dek\x18\n" +
	" \x01(\x03R\x03dek\x12\x14\n" +
	"\x05value\x18\v \x01(\fR\x05value\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompacted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vcompactedAt\x12\x1b\n" +
	"\tleader_id\x18\x0e \x01(\tR\bleaderId\x12?\n" +
	"\rreplicated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\freplicatedAt\x12\x10\n" +
	"\x03crc\x18\x01 \x01(\x04R\x03crcB+Z)github.com/netsy-dev/netsy/internal/protob\x06proto3"

var (
	file_proto_record_proto_rawDescOnce sync.Once
	file_proto_record_proto_rawDescData []byte
)

func file_proto_record_proto_rawDescGZIP() []byte {
	file_proto_record_proto_rawDescOnce.Do(func() {
		file_proto_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_record_proto_rawDesc), len(file_proto_record_proto_rawDesc)))
	})
	return file_proto_record_proto_rawDescData
}

var file_proto_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_record_proto_goTypes = []any{
	(*Record)(nil),                // 0: netsy.Record
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_proto_record_proto_depIdxs = []int32{
	1, // 0: netsy.Record.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: netsy.Record.compacted_at:type_name -> google.protobuf.Timestamp
	1, // 2: netsy.Record.replicated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_record_proto_init() }
func file_proto_record_proto_init() {
	if File_proto_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_record_proto_rawDesc), len(file_proto_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_record_proto_goTypes,
		DependencyIndexes: file_proto_record_proto_depIdxs,
		MessageInfos:      file_proto_record_proto_msgTypes,
	}.Build()
	File_proto_record_proto = out.File
	file_proto_record_proto_goTypes = nil
	file_proto_record_proto_depIdxs = nil
}
