// Netsy <https://netsy.dev>
// Copyright The Netsy Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/state.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthState represents the health of a Node.
type HealthState int32

const (
	HealthState_HEALTH_UNKNOWN  HealthState = 0
	HealthState_HEALTH_LOADING  HealthState = 1
	HealthState_HEALTH_HEALTHY  HealthState = 2
	HealthState_HEALTH_DEGRADED HealthState = 3
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "HEALTH_UNKNOWN",
		1: "HEALTH_LOADING",
		2: "HEALTH_HEALTHY",
		3: "HEALTH_DEGRADED",
	}
	HealthState_value = map[string]int32{
		"HEALTH_UNKNOWN":  0,
		"HEALTH_LOADING":  1,
		"HEALTH_HEALTHY":  2,
		"HEALTH_DEGRADED": 3,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_state_proto_enumTypes[0].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_proto_state_proto_enumTypes[0]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_proto_state_proto_rawDescGZIP(), []int{0}
}

// ElectorState represents whether a Node is the cluster Elector.
type ElectorState int32

const (
	ElectorState_ELECTOR_UNKNOWN  ElectorState = 0
	ElectorState_ELECTOR_FOLLOWER ElectorState = 1
	ElectorState_ELECTOR_LEADER   ElectorState = 2
)

// Enum value maps for ElectorState.
var (
	ElectorState_name = map[int32]string{
		0: "ELECTOR_UNKNOWN",
		1: "ELECTOR_FOLLOWER",
		2: "ELECTOR_LEADER",
	}
	ElectorState_value = map[string]int32{
		"ELECTOR_UNKNOWN":  0,
		"ELECTOR_FOLLOWER": 1,
		"ELECTOR_LEADER":   2,
	}
)

func (x ElectorState) Enum() *ElectorState {
	p := new(ElectorState)
	*p = x
	return p
}

func (x ElectorState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElectorState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_state_proto_enumTypes[1].Descriptor()
}

func (ElectorState) Type() protoreflect.EnumType {
	return &file_proto_state_proto_enumTypes[1]
}

func (x ElectorState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElectorState.Descriptor instead.
func (ElectorState) EnumDescriptor() ([]byte, []int) {
	return file_proto_state_proto_rawDescGZIP(), []int{1}
}

// PrimaryState represents a Node's role relative to the Primary.
type PrimaryState int32

const (
	PrimaryState_PRIMARY_UNKNOWN  PrimaryState = 0
	PrimaryState_PRIMARY_REPLICA  PrimaryState = 1
	PrimaryState_PRIMARY_STARTING PrimaryState = 2
	PrimaryState_PRIMARY_ACTIVE   PrimaryState = 3
	PrimaryState_PRIMARY_DRAINING PrimaryState = 4
)

// Enum value maps for PrimaryState.
var (
	PrimaryState_name = map[int32]string{
		0: "PRIMARY_UNKNOWN",
		1: "PRIMARY_REPLICA",
		2: "PRIMARY_STARTING",
		3: "PRIMARY_ACTIVE",
		4: "PRIMARY_DRAINING",
	}
	PrimaryState_value = map[string]int32{
		"PRIMARY_UNKNOWN":  0,
		"PRIMARY_REPLICA":  1,
		"PRIMARY_STARTING": 2,
		"PRIMARY_ACTIVE":   3,
		"PRIMARY_DRAINING": 4,
	}
)

func (x PrimaryState) Enum() *PrimaryState {
	p := new(PrimaryState)
	*p = x
	return p
}

func (x PrimaryState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrimaryState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_state_proto_enumTypes[2].Descriptor()
}

func (PrimaryState) Type() protoreflect.EnumType {
	return &file_proto_state_proto_enumTypes[2]
}

func (x PrimaryState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrimaryState.Descriptor instead.
func (PrimaryState) EnumDescriptor() ([]byte, []int) {
	return file_proto_state_proto_rawDescGZIP(), []int{2}
}

// NodeState is the full state triple carried in Heartbeats and Receipts,
// and returned by GetNodeState during election.
type NodeState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	HealthState    HealthState            `protobuf:"varint,2,opt,name=health_state,json=healthState,proto3,enum=netsy.HealthState" json:"health_state,omitempty"`
	ElectorState   ElectorState           `protobuf:"varint,3,opt,name=elector_state,json=electorState,proto3,enum=netsy.ElectorState" json:"elector_state,omitempty"`
	PrimaryState   PrimaryState           `protobuf:"varint,4,opt,name=primary_state,json=primaryState,proto3,enum=netsy.PrimaryState" json:"primary_state,omitempty"`
	LatestRevision int64                  `protobuf:"varint,5,opt,name=latest_revision,json=latestRevision,proto3" json:"latest_revision,omitempty"`
	StartTime      int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // used during election tiebreaker
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_proto_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_proto_state_proto_rawDescGZIP(), []int{0}
}

func (x *NodeState) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeState) GetHealthState() HealthState {
	if x != nil {
		return x.HealthState
	}
	return HealthState_HEALTH_UNKNOWN
}

func (x *NodeState) GetElectorState() ElectorState {
	if x != nil {
		return x.ElectorState
	}
	return ElectorState_ELECTOR_UNKNOWN
}

func (x *NodeState) GetPrimaryState() PrimaryState {
	if x != nil {
		return x.PrimaryState
	}
	return PrimaryState_PRIMARY_UNKNOWN
}

func (x *NodeState) GetLatestRevision() int64 {
	if x != nil {
		return x.LatestRevision
	}
	return 0
}

func (x *NodeState) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

// NodeInfo identifies a Node and how to reach it over the Peer API.
type NodeInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeId               string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MemberId             uint64                 `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	PeerAdvertiseAddress string                 `protobuf:"bytes,3,opt,name=peer_advertise_address,json=peerAdvertiseAddress,proto3" json:"peer_advertise_address,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_state_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *NodeInfo) GetPeerAdvertiseAddress() string {
	if x != nil {
		return x.PeerAdvertiseAddress
	}
	return ""
}

// ClusterState holds the current Elector and Primary as seen by the cluster.
// Pushed to every Node by the Elector whenever either role changes.
type ClusterState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elector       *NodeInfo              `protobuf:"bytes,1,opt,name=elector,proto3" json:"elector,omitempty"`
	Primary       *NodeInfo              `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`                       // empty if no Primary elected
	NodeCount     int32                  `protobuf:"varint,3,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"` // total registered Nodes for quorum calculation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterState) Reset() {
	*x = ClusterState{}
	mi := &file_proto_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterState) ProtoMessage() {}

func (x *ClusterState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterState.ProtoReflect.Descriptor instead.
func (*ClusterState) Descriptor() ([]byte, []int) {
	return file_proto_state_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterState) GetElector() *NodeInfo {
	if x != nil {
		return x.Elector
	}
	return nil
}

func (x *ClusterState) GetPrimary() *NodeInfo {
	if x != nil {
		return x.Primary
	}
	return nil
}

func (x *ClusterState) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

var File_proto_state_proto protoreflect.FileDescriptor

const file_proto_state_proto_rawDesc = "" +
	"\n" +
	"\x11proto/state.proto\x12\x05netsy\"\x97\x02\n" +
	"\tNodeState\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x125\n" +
	"\fhealth_state\x18\x02 \x01(\x0e2\x12.netsy.HealthStateR\vhealthState\x128\n" +
	"\relector_state\x18\x03 \x01(\x0e2\x13.netsy.ElectorStateR\felectorState\x128\n" +
	"\rprimary_state\x18\x04 \x01(\x0e2\x13.netsy.PrimaryStateR\fprimaryState\x12'\n" +
	"\x0flatest_revision\x18\x05 \x01(\x03R\x0elatestRevision\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\"v\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x04R\bmemberId\x124\n" +
	"\x16peer_advertise_address\x18\x03 \x01(\tR\x14peerAdvertiseAddress\"\x83\x01\n" +
	"\fClusterState\x12)\n" +
	"\aelector\x18\x01 \x01(\v2\x0f.netsy.NodeInfoR\aelector\x12)\n" +
	"\aprimary\x18\x02 \x01(\v2\x0f.netsy.NodeInfoR\aprimary\x12\x1d\n" +
	"\n" +
	"node_count\x18\x03 \x01(\x05R\tnodeCount*^\n" +
	"\vHealthState\x12\x12\n" +
	"\x0eHEALTH_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eHEALTH_LOADING\x10\x01\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x02\x12\x13\n" +
	"\x0fHEALTH_DEGRADED\x10\x03*M\n" +
	"\fElectorState\x12\x13\n" +
	"\x0fELECTOR_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10ELECTOR_FOLLOWER\x10\x01\x12\x12\n" +
	"\x0eELECTOR_LEADER\x10\x02*x\n" +
	"\fPrimaryState\x12\x13\n" +
	"\x0fPRIMARY_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fPRIMARY_REPLICA\x10\x01\x12\x14\n" +
	"\x10PRIMARY_STARTING\x10\x02\x12\x12\n" +
	"\x0ePRIMARY_ACTIVE\x10\x03\x12\x14\n" +
	"\x10PRIMARY_DRAINING\x10\x04B+Z)github.com/netsy-dev/netsy/internal/protob\x06proto3"

var (
	file_proto_state_proto_rawDescOnce sync.Once
	file_proto_state_proto_rawDescData []byte
)

func file_proto_state_proto_rawDescGZIP() []byte {
	file_proto_state_proto_rawDescOnce.Do(func() {
		file_proto_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_state_proto_rawDesc), len(file_proto_state_proto_rawDesc)))
	})
	return file_proto_state_proto_rawDescData
}

var file_proto_state_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_state_proto_goTypes = []any{
	(HealthState)(0),     // 0: netsy.HealthState
	(ElectorState)(0),    // 1: netsy.ElectorState
	(PrimaryState)(0),    // 2: netsy.PrimaryState
	(*NodeState)(nil),    // 3: netsy.NodeState
	(*NodeInfo)(nil),     // 4: netsy.NodeInfo
	(*ClusterState)(nil), // 5: netsy.ClusterState
}
var file_proto_state_proto_depIdxs = []int32{
	0, // 0: netsy.NodeState.health_state:type_name -> netsy.HealthState
	1, // 1: netsy.NodeState.elector_state:type_name -> netsy.ElectorState
	2, // 2: netsy.NodeState.primary_state:type_name -> netsy.PrimaryState
	4, // 3: netsy.ClusterState.elector:type_name -> netsy.NodeInfo
	4, // 4: netsy.ClusterState.primary:type_name -> netsy.NodeInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_state_proto_init() }
func file_proto_state_proto_init() {
	if File_proto_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_state_proto_rawDesc), len(file_proto_state_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_state_proto_goTypes,
		DependencyIndexes: file_proto_state_proto_depIdxs,
		EnumInfos:         file_proto_state_proto_enumTypes,
		MessageInfos:      file_proto_state_proto_msgTypes,
	}.Build()
	File_proto_state_proto = out.File
	file_proto_state_proto_goTypes = nil
	file_proto_state_proto_depIdxs = nil
}
