// Netsy <https://netsy.dev>
// Copyright The Netsy Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/upload.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Upload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	FileKind      FileKind               `protobuf:"varint,2,opt,name=file_kind,json=fileKind,proto3,enum=netsy.FileKind" json:"file_kind,omitempty"`
	RecordsCount  int64                  `protobuf:"varint,3,opt,name=records_count,json=recordsCount,proto3" json:"records_count,omitempty"`
	FirstRevision int64                  `protobuf:"varint,4,opt,name=first_revision,json=firstRevision,proto3" json:"first_revision,omitempty"`
	LastRevision  int64                  `protobuf:"varint,5,opt,name=last_revision,json=lastRevision,proto3" json:"last_revision,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	LeaderId      string                 `protobuf:"bytes,7,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upload) Reset() {
	*x = Upload{}
	mi := &file_proto_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upload) ProtoMessage() {}

func (x *Upload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upload.ProtoReflect.Descriptor instead.
func (*Upload) Descriptor() ([]byte, []int) {
	return file_proto_upload_proto_rawDescGZIP(), []int{0}
}

func (x *Upload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Upload) GetFileKind() FileKind {
	if x != nil {
		return x.FileKind
	}
	return FileKind_KIND_UNKNOWN
}

func (x *Upload) GetRecordsCount() int64 {
	if x != nil {
		return x.RecordsCount
	}
	return 0
}

func (x *Upload) GetFirstRevision() int64 {
	if x != nil {
		return x.FirstRevision
	}
	return 0
}

func (x *Upload) GetLastRevision() int64 {
	if x != nil {
		return x.LastRevision
	}
	return 0
}

func (x *Upload) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *Upload) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

var File_proto_upload_proto protoreflect.FileDescriptor

const file_proto_upload_proto_rawDesc = "" +
	"\n" +
	"\x12proto/upload.proto\x12\x05netsy\x1a\x10proto/file.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x02\n" +
	"\x06Upload\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\tfile_kind\x18\x02 \x01(\x0e2\x0f.netsy.FileKindR\bfileKind\x12#\n" +
	"\rrecords_count\x18\x03 \x01(\x03R\frecordsCount\x12%\n" +
	"\x0efirst_revision\x18\x04 \x01(\x03R\rfirstRevision\x12#\n" +
	"\rlast_revision\x18\x05 \x01(\x03R\flastRevision\x12;\n" +
	"\vuploaded_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\x12\x1b\n" +
	"\tleader_id\x18\a \x01(\tR\bleaderIdB+Z)github.com/netsy-dev/netsy/internal/protob\x06proto3"

var (
	file_proto_upload_proto_rawDescOnce sync.Once
	file_proto_upload_proto_rawDescData []byte
)

func file_proto_upload_proto_rawDescGZIP() []byte {
	file_proto_upload_proto_rawDescOnce.Do(func() {
		file_proto_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_upload_proto_rawDesc), len(file_proto_upload_proto_rawDesc)))
	})
	return file_proto_upload_proto_rawDescData
}

var file_proto_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_upload_proto_goTypes = []any{
	(*Upload)(nil),                // 0: netsy.Upload
	(FileKind)(0),                 // 1: netsy.FileKind
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_upload_proto_depIdxs = []int32{
	1, // 0: netsy.Upload.file_kind:type_name -> netsy.FileKind
	2, // 1: netsy.Upload.uploaded_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_upload_proto_init() }
func file_proto_upload_proto_init() {
	if File_proto_upload_proto != nil {
		return
	}
	file_proto_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_upload_proto_rawDesc), len(file_proto_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_upload_proto_goTypes,
		DependencyIndexes: file_proto_upload_proto_depIdxs,
		MessageInfos:      file_proto_upload_proto_msgTypes,
	}.Build()
	File_proto_upload_proto = out.File
	file_proto_upload_proto_goTypes = nil
	file_proto_upload_proto_depIdxs = nil
}
