# Netsy <https://netsy.dev>
# Copyright The Netsy Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "netsy.fullname" . }}-selfsigned
  labels:
    {{- include "netsy.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "netsy.fullname" . }}-ca
  labels:
    {{- include "netsy.labels" . | nindent 4 }}
spec:
  isCA: true
  secretName: {{ include "netsy.fullname" . }}-ca
  commonName: {{ required "clusterID is required" .Values.clusterID }}-ca
  duration: {{ .Values.tls.caDuration | quote }}
  issuerRef:
    name: {{ include "netsy.fullname" . }}-selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "netsy.fullname" . }}-ca
  labels:
    {{- include "netsy.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "netsy.fullname" . }}-ca
