# Netsy <https://netsy.dev>
# Copyright The Netsy Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "netsy.fullname" . }}
  labels:
    {{- include "netsy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "netsy.selectorLabels" . | nindent 4 }}
  ports:
    - name: client
      port: 2378
      targetPort: client
      protocol: TCP
    - name: peer
      port: 2381
      targetPort: peer
      protocol: TCP
    - name: election
      port: 8443
      targetPort: election
      protocol: TCP
    - name: health
      port: 8080
      targetPort: health
      protocol: TCP
