#!/usr/bin/env bash
# Netsy <https://netsy.dev>
# Copyright The Netsy Authors
# SPDX-License-Identifier: Apache-2.0
set -eo pipefail

echo "Running pre-commit checks..."
make precommit
echo "Pre-commit checks passed."
